name: flutter_miniapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # Your other regular dependencies here
  provider: ^4.0.0
  dio: ^3.0.9
  json_annotation: ^2.0.0
  shared_preferences: '<2.0.0'
  # floor: ^0.13.0
  device_info: 0.4.0+2
  permission_handler: ^3.2.2
  flutter_easyrefresh: ^2.0.4
  sqflite: ^1.3.0
  event_bus: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Your other dev_dependencies here
  json_model: ^0.0.2
  json_serializable: ^2.0.0
  build_runner: ^1.0.0
  # floor_generator: ^0.13.0
  # build_runner: ^1.7.3

  


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
